### ISSUE TITLE
m1 芯片设备 本地 run make init 失败

### ISSUE THREAD

**Issue by frmachao** [ArcBlock/abtnode-docs#126]
安装过程中一共遇到 四个问题
- Error: Command failed: /bin/sh -c autoreconf -fiv
/bin/sh: autoreconf: command not found
- `Error: pngquant failed to build, make sure that libpng is installed`
- Failed to set up Chromium r756035! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
- ERR! sharp Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8

其中我无法解决的问题是`ERR! sharp Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8`
因为是其 依赖的`@arcblock/gatsby-theme-docs` 这个包中的`sharp`的版本是`0.26` ，这个版本不支持在 arm 设备上构建。
这里有个相关的issue : https://github.com/nuxt/image/issues/204#
作者给出的最佳解决方式是 升级 到0.28.x 版本之上
https://sharp.pixelplumbing.com/install#apple-m1.

## 详细描述：
https://www.notion.so/arcblock/abtnode-docs-73f43088d7df4e1ab5b02e78aa925268

**Comment by wangshijun** [comment]
@frmachao 我看关联 notion 文档里面已经解决了

```
"resolutions": {
  "sharp": "^0.28.0"
}
```

这部分直接提 pr 吧
